import settings
import time

driver = settings.DRIVER


def test_preprint_filters():
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[share_publish_type]=thesis")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[share_publish_type]=preprint")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[allow_submissions]=true")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[allow_submissions]=false")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[share_publish_type]=thesis&filter[allow_submissions]=true")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[share_publish_type]=thesis&filter[allow_submissions]=false")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[share_publish_type]=preprint&filter[allow_submissions]=true")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[share_publish_type]=preprint&filter[allow_submissions]=false")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[allow_submissions]=true&filter[share_publish_type]=thesis")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[allow_submissions]=false&filter[share_publish_type]=thesis")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[allow_submissions]=true&filter[share_publish_type]=preprint")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.get("https://api.osf.io/v2/preprint_providers/?filter[allow_submissions]=false&filter[share_publish_type]=preprint")
	assert driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/h1')
	time.sleep(10)
	driver.quit()