repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: double-quote-string-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  -   id: flake8
      args:
        # Match Black's default line length
        - "--max-line-length=88"
        - "--max-complexity=18"
- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
  - id: isort
    args: ["--profile=black",
           "--filter-files",
           "--force-grid-wrap=2",
           "--lines-after-imports=2"]
    files: \.py$
