repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: double-quote-string-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  -   id: flake8
